// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH72cM459rPAEdVaiK2V5F6Mu5yWUo54E',
    appId: '1:834527981472:web:2d886acc227332388a7ec5',
    messagingSenderId: '834527981472',
    projectId: 'fridgenote-adb0e',
    authDomain: 'fridgenote-adb0e.firebaseapp.com',
    storageBucket: 'fridgenote-adb0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvJXjto3fFBdDyb2DmMVjo8qNf-wbM18',
    appId: '1:834527981472:android:a31070b58f4fd7e08a7ec5',
    messagingSenderId: '834527981472',
    projectId: 'fridgenote-adb0e',
    storageBucket: 'fridgenote-adb0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPEb-TLiUHdwq8gOCH9AUXa_pJZgsGWEw',
    appId: '1:834527981472:ios:48d511470faf67228a7ec5',
    messagingSenderId: '834527981472',
    projectId: 'fridgenote-adb0e',
    storageBucket: 'fridgenote-adb0e.firebasestorage.app',
    iosBundleId: 'com.example.fridgeNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPEb-TLiUHdwq8gOCH9AUXa_pJZgsGWEw',
    appId: '1:834527981472:ios:48d511470faf67228a7ec5',
    messagingSenderId: '834527981472',
    projectId: 'fridgenote-adb0e',
    storageBucket: 'fridgenote-adb0e.firebasestorage.app',
    iosBundleId: 'com.example.fridgeNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH72cM459rPAEdVaiK2V5F6Mu5yWUo54E',
    appId: '1:834527981472:web:71918afb0f0d84688a7ec5',
    messagingSenderId: '834527981472',
    projectId: 'fridgenote-adb0e',
    authDomain: 'fridgenote-adb0e.firebaseapp.com',
    storageBucket: 'fridgenote-adb0e.firebasestorage.app',
  );
}
